version: '3'

services:
  db:
    image: mfashby/ysc-mysql-demo
    build: ../mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
     - 3306:3306

  api-server:
    image: mfashby/ysc-apiserver-demo
    build: ../sailraceserver
    restart: always
    environment:
     - APP_HOSTNAME
     - APP_ROOT
     - APP_PORT
     - LIVE_RELOAD
     - NODE_ENV

  front:
    image: mfashby/ysc-front-demo
    build: front
    environment:
     - "EXTERNAL_URL=localhost:8080"
     - "TLS_CONFIG=off"
    ports:
     - 8080:8080

  adminer:
    image: adminer
    ports: 
     - 8081:8080
