version: '3'

services:
  mysql:
    image: mfashby/ysc-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  api-server:
    image: mfashby/ysc-apiserver

  front:
    image: mfashby/ysc-front

  wordpress:
    image: mfashby/ysc-wordpress
    environment:
      WORDPRESS_DB_PASSWORD: example