version: '3'

services:
  front:
    environment:
     - "EXTERNAL_URL=http://localhost"
     - "TLS_CONFIG=off"
    ports:
     - "80:80"

  mysql:
    volumes:
     - "./mysql/sql/:/docker-entrypoint-initdb.d/"
     
  adminer:
    image: adminer
    ports: 
     - "8081:8080"
