version: '3'

services:
  front:
    environment:
     - "EXTERNAL_URL=http://localhost"
     - "TLS_CONFIG=off"
    ports:
     - "80:80"

  adminer:
    image: adminer
    ports: 
     - "8081:8080"
