version: '2'

services:
  mysql:
    image: mfashby/ysc-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
     - 3306:3306

  api-server:
    image: mfashby/ysc-apiserver
    environment:
     - DB_URL
    links: 
      - mysql
    depends_on:
      - mysql

  front:
    image: mfashby/ysc-front
    environment:
     - EXTERNAL_URL
     - TLS_CONFIG
    ports:
     - 80:80
    links:
     - wordpress
     - api-server
    fip: "169.197.100.5"

  wordpress:
    image: mfashby/ysc-wordpress
    environment:
      WORDPRESS_DB_PASSWORD: example
    links:
     - mysql

  adminer:
    image: adminer
    ports: 
     - 8081:8080
    links:
    - mysql:db
